// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdhgguquynvakmxghvok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkaGdndXF1eW52YWtteGdodm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzE4NzEsImV4cCI6MjA2ODcwNzg3MX0.qZkyGq44JpFWxl7p1bP_V8wiUG4FYtBoe_RJc83_jcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
console.log('Supabase client initialized');
// console.log('Supabase client initialized,', supabase);
// const { data, error } = await supabase
//   .from("user_progress")
//   .select("*")
//   .eq("user_id", "63f45578-5e97-42cd-88f2-176486dea7e0")
//   .eq("specialty", "pediatrics");

// if (error) console.error(error);
// else console.log(data);
